# Generated by Django 5.0.7 on 2024-07-21 14:29

import car_dealer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024, validators=[car_dealer.models.validate_year])),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seating_capacity', models.IntegerField(default=1)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semiautomatic', 'Semi-Automatic'), ('cvt', 'CVT')], default='manual', max_length=50)),
                ('miles', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('rating', models.IntegerField(default=0, validators=[car_dealer.models.validate_rating])),
            ],
        ),
    ]
