# Generated by Django 5.0.7 on 2024-07-19 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0002_car_miles_car_price_car_rating_car_seating_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Miles must be a positive number.')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0.'), django.core.validators.MaxValueValidator(5, message='Rating cannot be greater than 5.')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Seating capacity must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1886, message='The year must be later than 1886.'), django.core.validators.MaxValueValidator(2024, message='The year cannot be in the future.')]),
        ),
    ]
