# Generated by Django 5.0.7 on 2024-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0003_remove_car_model_alter_car_miles_alter_car_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
