# Generated by Django 5.0.7 on 2024-07-20 01:12

import car_dealer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0004_alter_car_miles_alter_car_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0, validators=[car_dealer.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semiautomatic', 'Semi-Automatic'), ('cvt', 'CVT')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2024, validators=[car_dealer.models.validate_year]),
        ),
    ]
